service: app
# app and org for use with dashboard.serverless.com
#app: hiupt
#org: byunjuneseok

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:*:*:*"
  environment:
    TABLE_NAME_USER: user-${opt:stage, self:provider.stage}

package:
  exclude:
    - ./**
    - ./api/**
    - ./api/**
    - ./go/**
  include:
    - ./bin/users/**

functions:
  userCreate:
    handler: bin/users/create
    events:
      - httpApi:
          path: /users/create
          method: post
  userRetrieve:
    handler: bin/users/retrieve
    events:
      - httpApi:
          path: /users/{id}
          method: get

resources:
  Resources:
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: user-${opt:stage, self:provider.stage}
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-offline